version: '3.8'

services:
  app:
    build: .
    container_name: faqs-app
    ports:
      - '3000:3000'
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    links:
      - db
    command: npm run start

  db:
    image: postgres:9.6-alpine
    restart: always
    container_name: db-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=faqs